branch-defaults:
  default:
    environment: configuration-service-0
global:
  application_name: configuration-service
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-east-1
  profile: eb-cli
  sc: null
